### ISSUE TITLE
Improve NACK generation algorithm

### ISSUE THREAD

**Issue by ibc** [ibc/mediasoup#72]
The [current NACK generation implementation](https://github.com/ibc/mediasoup/blob/master/worker/src/RTC/RtpStreamRecv.cpp#L143) and [NACK processing](https://github.com/ibc/mediasoup/blob/master/worker/src/RTC/RtpStreamSend.cpp#L76)  are too simple.

Let's learn from @ggarber's [post](http://www.rtcbits.com/2017/03/retransmissions-in-webrtc.html) (thanks!) and plan it after 1.0.0.

**Comment by jmillan** [comment]
NOTE:

If we don't receive a packet from the remote sender, even having NACK-ed it, that lost packet could make the  video freeze on the remote receiver.

Chrome waits for the full frame before passing it to the encoder. Meaning that if such packet does not arrive,  the frame does not get completed and thus the video is likely to get frozen.

https://bugs.chromium.org/p/webrtc/issues/detail?id=4903:
"
When nack is on, we will only pass the completed frame to decoder. So when there is no completed frame received, you will see freezing video. 
When nack is off, we will pass the current frame to decoder no matter it's completed or not. The output depends on how the decoder handles incomplete frame. If it can decode it out, you'll the artifacts. Otherwise it will fail and you will lost one frame.
SW decoder usually can handle incomplete frame much better than HW decoder, which mostly will fail.
"

We must then have more control over the missing packets. And above it IMHO, generate PLI ourself if there is a packet that didn't arrive within the expected time window.

**Comment by jmillan** [comment]
One of the things we can already do is sending a PLI as soon as we find a too long NACK list. For example, when the previous `RtpStreamRecv::lastSeq32` differs from the current one by more than the amount of packets we can represent on the NACK request.  Right now those packets are not being requested.

**Comment by jmillan** [comment]
Interesting info: https://bugs.chromium.org/p/webrtc/issues/detail?id=3339

It also points how to check whether a RTP packet is a keyframe (points to the RFC that points it :-)), so we can keep sending PLIs until the keyframe is received.

**Comment by ibc** [comment]
The keyframe detection may be done in the future as it's too hard for 1.0.0.

NACK generation has been already implemented, and retransmissions have been improved in 6ecc3ebe128f24b0a245f453bd4bcf6f6687a6e2, so let's close this issue :)
